/**
 * Success Message Codes
 */
export const SUCCESS_CODES = {
  CREATED: "RESOURCE_CREATED",
  UPDATED: "RESOURCE_UPDATED",
  DELETED: "RESOURCE_DELETED",
  RETRIEVED: "RESOURCE_RETRIEVED",
  LISTED: "RESOURCES_LISTED",
  LOGGED_IN: "LOGIN_SUCCESSFUL",
  OPERATION_COMPLETED: "OPERATION_COMPLETED",
} as const;

/**
 * Error Codes
 */
export const ERROR_CODES = {
  // Validation errors
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_INPUT: "INVALID_INPUT",
  MISSING_FIELD: "MISSING_FIELD",

  // Authentication errors
  INVALID_TOKEN: "INVALID_TOKEN",
  EXPIRED_TOKEN: "EXPIRED_TOKEN",
  MISSING_TOKEN: "MISSING_TOKEN",
  UNAUTHORIZED: "UNAUTHORIZED",

  // Authorization errors
  FORBIDDEN: "FORBIDDEN",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",

  // Resource errors
  NOT_FOUND: "NOT_FOUND",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",

  // Business logic errors
  INVALID_OPERATION: "INVALID_OPERATION",
  BUSINESS_RULE_VIOLATION: "BUSINESS_RULE_VIOLATION",

  // Server errors
  INTERNAL_ERROR: "INTERNAL_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
} as const;

export type SuccessCode = (typeof SUCCESS_CODES)[keyof typeof SUCCESS_CODES];
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
